---
- name: Deploy Apache
  hosts: azure-epsilon-vm-0
  become: true

  tasks:
    - name: Pull Docker Image
      community.docker.docker_image:
        name: "alex919090/apache_test:latest"
        source: pull

    - name: Run Docker Container
      community.docker.docker_container:
        name: my_apache
        image: alex919090/apache_test:latest
        state: started
        published_ports:
          - "80:80"

- name: Deploy .NET
  hosts: azure-epsilon-vm-1
  become: true

  tasks:
    - name: Pull Docker Image
      community.docker.docker_image:
        name: "alex919090/dotnet_test:latest"
        source: pull

    - name: Run Docker Container
      community.docker.docker_container:
        name: my_dotnet
        image: alex919090/dotnet_test:latest
        state: started
        published_ports:
          - "80:80"

# - name: Deploy Java
#   hosts: azure-epsilon-vm-2
#   become: true

#   tasks:
#     - name: Pull Docker Image
#       community.docker.docker_image:
#         name: "alex919090/java_test:latest"
#         source: pull

#     - name: Run Docker Container
#       community.docker.docker_container:
#         name: my_java
#         image: alex919090/java_test:latest
#         state: started
#         published_ports:
#           - "80:80"

# - name: Deploy Maven
#   hosts: azure-epsilon-vm-3
#   become: true

#   tasks:
#     - name: Pull Docker Image
#       community.docker.docker_image:
#         name: "alex919090/maven_test:latest"
#         source: pull

#     - name: Run Docker Container
#       community.docker.docker_container:
#         name: my_maven
#         image: alex919090/maven_test:latest
#         state: started
#         published_ports:
#           - "80:80"
